apiVersion: v1
kind: Service
metadata:
  name: vulnerable-web
  namespace: demo
  labels:
    app: vulnerable-web
spec:
  selector:
    app: vulnerable-web
  ports:
    - name: http
      port: 80
      targetPort: 8080
